directory: /music
library: /app/.beets/musiclibrary.db

art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no

import:
  move: yes            # Move files to /music
  write: yes           # Write tags if we run anything manually (safe here)
  copy: no
  delete: no
  autotag: no          # ❗ Explicitly disable metadata changes
  timid: yes           # Prevent any accidental overwrites
  resume: ask
  quiet_fallback: skip
  incremental: no
  log: /app/.beets/import.log

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title

plugins: web lastgenre scrub replaygain embedart extrafiles fetchart duplicates

web:
    host: 0.0.0.0
    port: 8337
    cors: yes

replaygain:
    auto: yes
    backend: ffmpeg

embedart:
    auto: yes
    maxwidth: 1000

fetchart:
    auto: yes
    cautious: yes
    cover_names: cover folder

extrafiles:
    patterns:
        all: ['*.jpg', '*.jpeg', '*.png', '*.pdf', '*.log', '*.cue', '*.m3u']
    paths:
        all: $albumpath/

scrub:
    auto: yes

lastgenre:
    auto: yes
    source: album

duplicates:
    checksum: ffmpeg